project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true

website:
  title: "ğŸ‘¨ğŸ»â€ğŸ’»"
  navbar:
    background: "#fff"
    foreground: "#303030"
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: research.qmd
        text: Pesquisa
      - href: about.qmd
        text: Sobre
    right: 
      - icon: twitter
        href: https://twitter.com/paulofelipeao
      - icon: github
        href: https://www.github.com/paulofelipe
  page-footer: 
    right: "Copyright 2023, Paulo Oliveira" 
format:
  html:
    theme:
      - mytheme.scss
    mainfont: Poppins
    toc: true



